name: Terraform Dev

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  TF_VERSION: 1.14.4

jobs:
  plan:
    name: Terraform Plan (dev)
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: envs/dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init -input=false
      - run: terraform validate
      - run: terraform plan

  apply:
    name: Terraform Apply (dev)
    needs: plan
    runs-on: ubuntu-latest
    environment: dev   # ðŸ‘ˆ approval happens HERE

    defaults:
      run:
        shell: bash
        working-directory: envs/dev

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init -input=false
      - run: terraform apply -auto-approve
