name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to destroy (dev / stage / prod)"
        required: true
        type: choice
        options:
          - dev
          - stage
          - prod

env:
  AWS_REGION: ap-south-1
  TF_VERSION: 1.14.4

jobs:
  plan-destroy:
    name: Terraform Destroy Plan
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: envs/${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init -input=false
      - run: terraform plan -destroy

  destroy:
    name: Terraform Destroy Apply
    needs: plan-destroy
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}  # ðŸ‘ˆ approval happens HERE

    defaults:
      run:
        shell: bash
        working-directory: envs/${{ github.event.inputs.environment }}

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - run: terraform init -input=false
      - run: terraform destroy -auto-approve
